[tool.poetry]
name = "django-bulma"
version = "0.8.1"
description = "Bulma CSS Framework for Django projects"
authors = ["Tim Kamanin <tim@timonweb.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://timonweb.com"
keywords = ["django", "css", "bulma", "theme"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Environment :: Web Environment",
    "Framework :: Django"
]
packages = [
    { include = "bulma" }
]

[tool.poetry.dependencies]
python = ">=3.6,<3.9"
django = ">=2.2,<3.2"

[tool.poetry.dev-dependencies]
pytest-django = "^3.8.0"
pytest = "^5.3.4"
tox = "^3.14.3"
beautifulsoup4 = "^4.8.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
